# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(631, 557)
        Form.setMinimumSize(QtCore.QSize(631, 557))
        Form.setMaximumSize(QtCore.QSize(631, 557))
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 601, 151))
        self.groupBox.setObjectName("groupBox")
        self.server_url = QtWidgets.QLineEdit(self.groupBox)
        self.server_url.setGeometry(QtCore.QRect(20, 30, 261, 20))
        self.server_url.setObjectName("server_url")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 50, 251, 16))
        self.label.setObjectName("label")
        self.secret_key = QtWidgets.QLineEdit(self.groupBox)
        self.secret_key.setGeometry(QtCore.QRect(20, 70, 261, 20))
        self.secret_key.setObjectName("secret_key")
        self.ret_str = QtWidgets.QLabel(self.groupBox)
        self.ret_str.setGeometry(QtCore.QRect(290, 30, 301, 41))
        self.ret_str.setObjectName("ret_str")
        self.copy_ret_str = QtWidgets.QPushButton(self.groupBox)
        self.copy_ret_str.setGeometry(QtCore.QRect(504, 80, 91, 23))
        self.copy_ret_str.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.copy_ret_str.setObjectName("copy_ret_str")
        self.gen_ret_str = QtWidgets.QPushButton(self.groupBox)
        self.gen_ret_str.setGeometry(QtCore.QRect(410, 80, 91, 23))
        self.gen_ret_str.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.gen_ret_str.setObjectName("gen_ret_str")
        self.group_token = QtWidgets.QLineEdit(self.groupBox)
        self.group_token.setGeometry(QtCore.QRect(20, 120, 261, 20))
        self.group_token.setEchoMode(QtWidgets.QLineEdit.Password)
        self.group_token.setObjectName("group_token")
        self.group_idInput = QtWidgets.QLineEdit(self.groupBox)
        self.group_idInput.setGeometry(QtCore.QRect(20, 100, 261, 20))
        self.group_idInput.setObjectName("group_idInput")
        self.start = QtWidgets.QPushButton(Form)
        self.start.setGeometry(QtCore.QRect(530, 520, 75, 23))
        self.start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start.setObjectName("start")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 160, 311, 21))
        self.label_2.setObjectName("label_2")
        self.requestsWidget = QtWidgets.QListWidget(Form)
        self.requestsWidget.setGeometry(QtCore.QRect(10, 180, 311, 331))
        self.requestsWidget.setObjectName("requestsWidget")
        self.requestBody = QtWidgets.QTextBrowser(Form)
        self.requestBody.setGeometry(QtCore.QRect(320, 180, 291, 331))
        self.requestBody.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.requestBody.setObjectName("requestBody")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(320, 160, 291, 21))
        self.label_3.setObjectName("label_3")
        self.work_status = QtWidgets.QLabel(Form)
        self.work_status.setGeometry(QtCore.QRect(406, 520, 121, 21))
        self.work_status.setObjectName("work_status")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Генератор callback запросов"))
        self.groupBox.setTitle(_translate("Form", "Информация о сервере"))
        self.server_url.setPlaceholderText(_translate("Form", "url сервера"))
        self.label.setText(_translate("Form", "Секретный ключ"))
        self.secret_key.setPlaceholderText(_translate("Form", "aaQ13axAPQEcczQa"))
        self.ret_str.setText(_translate("Form", "Строка, которую должен вернуть сервер: XXXXXXX"))
        self.copy_ret_str.setText(_translate("Form", "Скопировать"))
        self.gen_ret_str.setText(_translate("Form", "Сгенерировать"))
        self.group_token.setPlaceholderText(_translate("Form", "токен группы"))
        self.group_idInput.setPlaceholderText(_translate("Form", "id группы"))
        self.start.setText(_translate("Form", "Запуск"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">Запросы</p></body></html>"))
        self.requestBody.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">Тело запроса</p></body></html>"))
        self.work_status.setText(_translate("Form", "<html><head/><body><p><img src=\":/response_codes/Sending.png\"/> Сервер не запущен</p></body></html>"))
import source_rc
